-- 문제1) 사원들의 이름, 부서번호, 부서명을 출력하라
SELECT E.FIRST_NAME,
       E.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 문제2) 30번 부서의 사원들의 이름,직업,부서명을 출력하라
-- E.JOB_ID = J.JOB_ID // E.DEPARTMENT_ID = D.DEPARTMENT_ID
SELECT E.FIRST_NAME,
       E.JOB_ID,
       J.JOB_TITLE,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D, JOBS J
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND E.JOB_ID = J.JOB_ID
    AND D.DEPARTMENT_ID = 30;

-- 문제3) 커미션을 받는 사원의 이름, 직업, 부서번호,부서명을 출력하라
SELECT E.FIRST_NAME,
       J.JOB_TITLE,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E, JOBS J, DEPARTMENTS D
WHERE E.COMMISSION_PCT IS NOT NULL
      AND E.DEPARTMENT_ID = D.DEPARTMENT_ID
      AND J.JOB_ID = E.JOB_ID;

-- 문제4) 지역번호 2500 에서 근무하는 사원의 이름, 직업,부서번호,부서명을 출력하라
SELECT E.FIRST_NAME,
       E.JOB_ID,
       D.DEPARTMENT_ID,
       D.DEPARTMENT_NAME,
       D.LOCATION_ID
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS L
WHERE D.DEPARTMENT_ID = E.DEPARTMENT_ID
  AND D.LOCATION_ID = L.LOCATION_ID
  AND D.LOCATION_ID = 2500;

-- 문제5) 이름에 A가 들어가는 사원들의 이름과 부서이름을 출력하라
SELECT N.FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES N, DEPARTMENTS D
WHERE N.FIRST_NAME LIKE '%A%'
  AND N.DEPARTMENT_ID = D.DEPARTMENT_ID

-- 문제6) 사원이름과 그 사원의 관리자 이름을 출력하라 ... 같은 테이블을 다른 테이블로 생각
SELECT EMP.FIRST_NAME AS COUNT, MGR.FIRST_NAME AS MANAGER
FROM EMPLOYEES EMP, EMPLOYEES MGR
WHERE EMP.MANAGER_ID = MGR.EMPLOYEE_ID;

-- 문제7) 사원이름과 부서명과 월급을 출력하는데 월급이 3000 이상인 사원을 출력하라
SELECT *
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
    AND E.SALARY >= 3000

-- 문제8) TJ 이란 사원보다 늦게 입사한 사원의 이름과 입사일을 출력하라
SELECT P.FIRST_NAME, P.HIRE_DATE, Q.FIRST_NAME, Q.HIRE_DATE
FROM EMPLOYEES P, EMPLOYEES Q
WHERE P.FIRST_NAME = 'TJ'
    AND P.HIRE_DATE < Q.HIRE_DATE
ORDER BY Q.HIRE_DATE ASC;

-- 문제9) 급여가 3000에서 5000사이인 사원의 이름과 소속부서명 출력하라
SELECT E.FIRST_NAME,
       D.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE (E.SALARY BETWEEN 3000 AND 5000)
  AND (E.DEPARTMENT_ID = D.DEPARTMENT_ID);

-- 문제10) ACCOUNTING 부서 소속 사원의 이름과 입사일 출력하라
SELECT E.FIRST_NAME, E.HIRE_DATE, d.DEPARTMENT_NAME
FROM EMPLOYEES E, DEPARTMENTS D
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND D.DEPARTMENT_NAME = 'Accounting'

-- 문제11) 급여가 3000이하인 사원의 이름과 급여, 근무지를 출력하라.
SELECT E.FIRST_NAME, E.SALARY, D.LOCATION_ID, C.CITY
FROM EMPLOYEES E, DEPARTMENTS D, LOCATIONS C
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID
  AND C.LOCATION_ID = D.LOCATION_ID
  AND E.SALARY <= 3000
